name: Generate Snake
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: TahaFarashi
          outputs: dist/github-contribution-grid-snake.svg

      - name: Upload Snake SVG
        uses: actions/upload-artifact@v3
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg
